# Generated by Django 5.1.4 on 2025-01-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('descriptions', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='details')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
