# Generated by Django 5.1.4 on 2025-01-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0003_playerimage_delete_detail_product_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerimage',
            name='subtitle',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
