# Generated by Django 5.1.4 on 2025-01-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0004_playerimage_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerimage',
            name='subtitle',
        ),
    ]
