# Generated by Django 5.1.4 on 2025-02-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0005_remove_playerimage_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerimage',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
